from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
    Table,
    TableStyle,
    PageBreak
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER
from datetime import datetime
import os
from reportlab.lib.pagesizes import A4

def create_pdf(

    output_path,

    crop_name,

    plant_id,

    field_name,

    disease,

    status,

    confidence,

    city,

    temperature,

    humidity,

    weather,

    scan_date,

    image_path,

    ai_chat

):

    doc = SimpleDocTemplate(output_path)

    styles = getSampleStyleSheet()

    title = styles["Title"]
    title.alignment = TA_CENTER

    heading = styles["Heading2"]
    normal = styles["BodyText"]

    story = []

    # ===========================================
    # TITLE
    # ===========================================

    story.append(
        Paragraph(
            "🌿 CropCareAI",
            title
        )
    )

    story.append(
        Paragraph(
            "<b>AI Crop Monitoring Report</b>",
            heading
        )
    )

    story.append(Spacer(1, 20))

    # ===========================================
    # PLANT INFORMATION
    # ===========================================

    story.append(
        Paragraph("<b>Plant Information</b>", heading)
    )

    table = Table(

        [

            ["Crop", crop_name],

            ["Plant ID", plant_id],

            ["Field", field_name],

            ["Scan Date", scan_date]

        ],

        colWidths=[120, 300]

    )

    table.setStyle(

        TableStyle([

            ("GRID", (0,0), (-1,-1), 1, colors.grey),

            ("BACKGROUND", (0,0), (0,-1), colors.lightgreen),

            ("FONTNAME", (0,0), (-1,-1), "Helvetica"),

            ("BOTTOMPADDING", (0,0), (-1,-1), 8)

        ])

    )

    story.append(table)

    story.append(Spacer(1,15))

    # ===========================================
    # IMAGE
    # ===========================================

    if os.path.exists(image_path):

        img = Image(image_path)

        img.drawWidth = 3.5 * inch
        img.drawHeight = 3.5 * inch

        story.append(img)

        story.append(Spacer(1,15))

    # ===========================================
    # DISEASE
    # ===========================================

    story.append(
        Paragraph("<b>Disease Analysis</b>", heading)
    )

    disease_table = Table(

        [

            ["Disease", disease],

            ["Status", status],

            ["Confidence", f"{confidence:.2f}%"]

        ],

        colWidths=[120,300]

    )

    disease_table.setStyle(

        TableStyle([

            ("GRID",(0,0),(-1,-1),1,colors.grey),

            ("BACKGROUND",(0,0),(0,-1),colors.beige),

            ("BOTTOMPADDING",(0,0),(-1,-1),8)

        ])

    )

    story.append(disease_table)

    story.append(Spacer(1,15))

    # ===========================================
    # WEATHER
    # ===========================================

    story.append(
        Paragraph("<b>Weather Report</b>", heading)
    )

    weather_table = Table(

        [

            ["City", city],

            ["Temperature", f"{temperature} °C"],

            ["Humidity", f"{humidity}%"],

            ["Weather", weather]

        ],

        colWidths=[120,300]

    )

    weather_table.setStyle(

        TableStyle([

            ("GRID",(0,0),(-1,-1),1,colors.grey),

            ("BACKGROUND",(0,0),(0,-1),colors.lightblue),

            ("BOTTOMPADDING",(0,0),(-1,-1),8)

        ])

    )

    story.append(weather_table)

    story.append(Spacer(1,15))

    # ===========================================
    # AI
    # ===========================================

    story.append(
        Paragraph("<b>AI Recommendation</b>", heading)
    )

    story.append(

        Paragraph(

            ai_chat.replace("\n","<br/>"),

            normal

        )

    )

    story.append(Spacer(1,20))

    # ===========================================
    # FOOTER
    # ===========================================

    story.append(

        Paragraph(

            f"Generated by CropCareAI on {datetime.now().strftime('%d %b %Y %H:%M')}",

            styles["Italic"]

        )

    )

    doc.build(story)

def create_complete_report(
    output_path,
    history
):

    if not history:
        return

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=35,
        rightMargin=35,
        topMargin=35,
        bottomMargin=35
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    heading_style = styles["Heading2"]

    normal_style = styles["BodyText"]

    story = []

    doc.build(story)
    # ==================================================
    # CropCareAI Logo
    # ==================================================

    story.append(
        Paragraph(
            "<font color='darkgreen'><b> CropCareAI</b></font>",
            title_style
        )
    )

    story.append(
        Paragraph(
            "<para align='center'><b>AI Powered Crop Monitoring System</b></para>",
            normal_style
        )
    )

    story.append(Spacer(1, 25))

    # ==================================================
    # Report Title
    # ==================================================

    story.append(
        Paragraph(
            "<para align='center'><font size='18'><b>COMPLETE PLANT REPORT</b></font></para>",
            heading_style
        )
    )

    story.append(Spacer(1, 40))

    crop_name = history[0][0]
    plant_id = history[0][1]
    field_name = history[0][2]

        # ============================================
    # Plant Summary
    # ============================================

    healthy_scans = sum(
        1 for row in history
        if "Healthy" in row[5]
    )

    diseased_scans = len(history) - healthy_scans

    latest_scan = history[-1]

    latest_status = latest_scan[5]
    latest_disease = latest_scan[4]

    if "Healthy" in latest_status:

        status_html = "<font color='green'><b>Healthy</b></font>"

    else:

        status_html = "<font color='red'><b>Diseased</b></font>"

    summary_data = [

    ["Crop", crop_name],

    ["Plant ID", plant_id],

    ["Field", field_name],

    ["Total Scans", len(history)],

    ["Healthy Scans", healthy_scans],

    ["Diseased Scans", diseased_scans],

    ["Current Status", Paragraph(status_html, normal_style)],

    ["Latest Disease", latest_disease],

    [
        "Generated On",
        datetime.now().strftime("%d %b %Y %I:%M %p")
    ]

]
    summary_table = Table(
        summary_data,
        colWidths=[140, 320]
    )

    summary_table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(0,-1),colors.darkgreen),

            ("TEXTCOLOR",(0,0),(0,-1),colors.white),

            ("BACKGROUND",(1,0),(1,-1),colors.whitesmoke),

            ("GRID",(0,0),(-1,-1),0.5,colors.grey),

            ("BOTTOMPADDING",(0,0),(-1,-1),8),

            ("TOPPADDING",(0,0),(-1,-1),8),

            ("FONTNAME",(0,0),(0,-1),"Helvetica-Bold"),
("FONTNAME",(1,0),(1,-1),"Helvetica"),

        ])

    )

    story.append(summary_table)

    story.append(Spacer(1,30))
    story.append(
        Paragraph(
            "<font size='16'><b>SCAN HISTORY</b></font>",
            heading_style
        )
    )

    story.append(Spacer(1,15))
    scan_number = len(history)

    for scan in history:

        (
            crop_name,
            plant_id,
            field_name,

            image_path,

            disease,

            status,

            confidence,

            city,

            temperature,

            humidity,

            pressure,

            wind_speed,

            weather,

            ai_chat,

            scan_date

        ) = scan
        if "Healthy" in status:

            status_color = colors.green

        else:

            status_color = colors.red


        story.append(

            Table(

                [[
                    Paragraph(
                        f"<b>Scan #{scan_number}</b>",
                        heading_style
                    ),

                    Paragraph(
                        scan_date,
                        normal_style
                    )

                ]],

                colWidths=[260,210]

            )

        )

        story.append(Spacer(1,10))
    if os.path.exists(image_path):

        img = Image(image_path)

        img.drawWidth = 2.7 * inch

        img.drawHeight = 2.7 * inch
        story.append(img)
        story.append(Spacer(1,10))
        city = city.replace("■", "a")
        details = [

        ["Disease", disease],

       [
    "Status",
    Paragraph(
        "<font color='red'><b>Diseased</b></font>"
        if "Diseased" in status
        else "<font color='green'><b>Healthy</b></font>",
        normal_style
    )
],

        ["Confidence", f"{confidence:.2f}%"],

        ["City", city],

        ["Temperature", f"{temperature} °C"],

        ["Humidity", f"{humidity}%"],

        ["Weather", weather]

    ]
        details_table = Table(

        details,

        colWidths=[140,330]

    )

    details_table.setStyle(

        TableStyle([

            ("GRID",(0,0),(-1,-1),0.5,colors.grey),

            ("BACKGROUND",(0,0),(0,-1),colors.HexColor("#E8F5E9")),

            ("BOTTOMPADDING",(0,0),(-1,-1),7),

            ("TOPPADDING",(0,0),(-1,-1),7),

            ("FONTNAME",(0,0),(0,-1),"Helvetica-Bold")

        ])

    )

    story.append(details_table)

    story.append(Spacer(1,10))
    if ai_chat:

        story.append(

            Paragraph(

                "<b>AI Recommendation</b>",

                heading_style

            )

        )

        story.append(

            Paragraph(

                ai_chat.replace("\n","<br/>"),

                normal_style

            )

        )

    story.append(Spacer(1,20))

    story.append(

        Table(

            [[""]],

            colWidths=[500],

            rowHeights=[1],

            style=TableStyle([

                ("BACKGROUND",(0,0),(-1,-1),colors.lightgrey)

            ])

        )

    )

    story.append(Spacer(1,20))

    scan_number -= 1
        
    story.append(
        Table(
            [[""]],
            colWidths=[500],
            rowHeights=[2],
            style=TableStyle([
                ("BACKGROUND", (0,0), (-1,-1), colors.darkgreen)
            ])
        )
    )

    story.append(Spacer(1, 30))

    doc.build(story)